apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter-deployment
  labels:
    app: formatter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formatter
  template:
    metadata:
      labels:
        app: formatter
    spec:
      containers:
        - name: formatter
          image: indosaram/formatter:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: formatter-service
spec:
  type: NodePort
  selector:
    app: formatter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formatter-ingress
spec:
  rules:
    - host: example.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: formatter-service
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: formatter-ingress-service
spec:
  ports:
    - name: service
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: formatter-ingress
    app.kubernetes.io/part-of: formatter-ingress
