// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: lang_server/lang_server.proto

package lang_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang      string   `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Formatter string   `protobuf:"bytes,2,opt,name=formatter,proto3" json:"formatter,omitempty"`
	Code      string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Args      []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lang_server_lang_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_lang_server_lang_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_lang_server_lang_server_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Input) GetFormatter() string {
	if x != nil {
		return x.Formatter
	}
	return ""
}

func (x *Input) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Input) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type FormattedCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormattedCode string `protobuf:"bytes,1,opt,name=formatted_code,json=formattedCode,proto3" json:"formatted_code,omitempty"`
}

func (x *FormattedCode) Reset() {
	*x = FormattedCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lang_server_lang_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormattedCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattedCode) ProtoMessage() {}

func (x *FormattedCode) ProtoReflect() protoreflect.Message {
	mi := &file_lang_server_lang_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattedCode.ProtoReflect.Descriptor instead.
func (*FormattedCode) Descriptor() ([]byte, []int) {
	return file_lang_server_lang_server_proto_rawDescGZIP(), []int{1}
}

func (x *FormattedCode) GetFormattedCode() string {
	if x != nil {
		return x.FormattedCode
	}
	return ""
}

var File_lang_server_lang_server_proto protoreflect.FileDescriptor

var file_lang_server_lang_server_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6c, 0x61,
	0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x05,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x36, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x43, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12,
	0x3b, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6c,
	0x61, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x44, 0x5a, 0x42,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x6e, 0x64, 0x6f, 0x73,
	0x61, 0x72, 0x61, 0x6d, 0x2f, 0x67, 0x6f, 0x6d, 0x75, 0x6e, 0x6b, 0x6f, 0x6e, 0x67, 0x2f, 0x67,
	0x6f, 0x6d, 0x75, 0x6e, 0x6b, 0x6f, 0x6e, 0x67, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lang_server_lang_server_proto_rawDescOnce sync.Once
	file_lang_server_lang_server_proto_rawDescData = file_lang_server_lang_server_proto_rawDesc
)

func file_lang_server_lang_server_proto_rawDescGZIP() []byte {
	file_lang_server_lang_server_proto_rawDescOnce.Do(func() {
		file_lang_server_lang_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_lang_server_lang_server_proto_rawDescData)
	})
	return file_lang_server_lang_server_proto_rawDescData
}

var file_lang_server_lang_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lang_server_lang_server_proto_goTypes = []interface{}{
	(*Input)(nil),         // 0: lang_server.Input
	(*FormattedCode)(nil), // 1: lang_server.FormattedCode
}
var file_lang_server_lang_server_proto_depIdxs = []int32{
	0, // 0: lang_server.Lang.Formatter:input_type -> lang_server.Input
	1, // 1: lang_server.Lang.Formatter:output_type -> lang_server.FormattedCode
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lang_server_lang_server_proto_init() }
func file_lang_server_lang_server_proto_init() {
	if File_lang_server_lang_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lang_server_lang_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lang_server_lang_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormattedCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lang_server_lang_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lang_server_lang_server_proto_goTypes,
		DependencyIndexes: file_lang_server_lang_server_proto_depIdxs,
		MessageInfos:      file_lang_server_lang_server_proto_msgTypes,
	}.Build()
	File_lang_server_lang_server_proto = out.File
	file_lang_server_lang_server_proto_rawDesc = nil
	file_lang_server_lang_server_proto_goTypes = nil
	file_lang_server_lang_server_proto_depIdxs = nil
}
