// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lang_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LangClient is the client API for Lang service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LangClient interface {
	Formatter(ctx context.Context, in *Input, opts ...grpc.CallOption) (*FormattedCode, error)
}

type langClient struct {
	cc grpc.ClientConnInterface
}

func NewLangClient(cc grpc.ClientConnInterface) LangClient {
	return &langClient{cc}
}

func (c *langClient) Formatter(ctx context.Context, in *Input, opts ...grpc.CallOption) (*FormattedCode, error) {
	out := new(FormattedCode)
	err := c.cc.Invoke(ctx, "/lang_server.Lang/Formatter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LangServer is the server API for Lang service.
// All implementations must embed UnimplementedLangServer
// for forward compatibility
type LangServer interface {
	Formatter(context.Context, *Input) (*FormattedCode, error)
	mustEmbedUnimplementedLangServer()
}

// UnimplementedLangServer must be embedded to have forward compatible implementations.
type UnimplementedLangServer struct {
}

func (UnimplementedLangServer) Formatter(context.Context, *Input) (*FormattedCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Formatter not implemented")
}
func (UnimplementedLangServer) mustEmbedUnimplementedLangServer() {}

// UnsafeLangServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LangServer will
// result in compilation errors.
type UnsafeLangServer interface {
	mustEmbedUnimplementedLangServer()
}

func RegisterLangServer(s grpc.ServiceRegistrar, srv LangServer) {
	s.RegisterService(&Lang_ServiceDesc, srv)
}

func _Lang_Formatter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LangServer).Formatter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lang_server.Lang/Formatter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LangServer).Formatter(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

// Lang_ServiceDesc is the grpc.ServiceDesc for Lang service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lang_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lang_server.Lang",
	HandlerType: (*LangServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Formatter",
			Handler:    _Lang_Formatter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lang_server/lang_server.proto",
}
